# Generated by Django 5.0.7 on 2025-06-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cfdi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('business_name', models.CharField(max_length=150, unique=True, verbose_name='Razón Social')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Cfdi',
                'verbose_name_plural': 'Cfdis',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('Nombre_Razon_Social', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('Nombre_Corto', models.CharField(default='', max_length=3, verbose_name='Corto')),
                ('RFC', models.CharField(max_length=13)),
                ('CURP', models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP')),
                ('Calle_No_Colonia', models.CharField(max_length=50, verbose_name='Calle_No_Colonia')),
                ('CODIGO_POSTAL', models.CharField(max_length=5, verbose_name='CODIGO_POSTAL')),
                ('Entidad', models.CharField(max_length=30, verbose_name='Entidad')),
                ('Municipio_Alcaldía', models.CharField(max_length=30, verbose_name='Municipio_Alcaldía')),
            ],
            options={
                'verbose_name': 'Contribuyente',
                'verbose_name_plural': 'Contribuyentes',
                'ordering': ['Nombre_Razon_Social'],
            },
        ),
    ]
