# Generated by Django 5.0.7 on 2025-06-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0002_historicalcfdi_historicalcontribuyente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cfdi',
        ),
        migrations.DeleteModel(
            name='HistoricalCfdi',
        ),
    ]
